# Generated by Django 3.1.6 on 2021-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210725_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='remark',
            new_name='admin_remark',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicationStatus',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='applicant_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='createdBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ApplicantTransactionDetail',
        ),
    ]
