# Generated by Django 3.1.6 on 2021-08-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_applicantfacilities_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRenewalTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionID', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionDate', models.CharField(blank=True, max_length=100, null=True)),
                ('receiptFile', models.FileField(blank=True, null=True, upload_to='TransactionReceiptForRenewal')),
                ('remark', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('applicantID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.applicant')),
            ],
        ),
    ]
