# Generated by Django 3.1.6 on 2021-08-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_applicationrenewaltransactiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='expiryDate',
        ),
    ]
