# Generated by Django 3.1.6 on 2021-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_applicant_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationrenewaltransactiondetail',
            name='receiptFile',
            field=models.FileField(blank=True, null=True, upload_to='TransactionReceipt'),
        ),
    ]
